version: 2
jobs:
  build:
    working_directory: ~/syme
    docker:
      # Since we include lein in the repo, all we need is a JDK.
      - image: openjdk:8
      - image: postgres:9.4.1
        # The official Postgres docker images will create your DB for you
        # if you set the POSTGRES_DB environment variable.
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: syme
    environment:
      # Suppress warnings by setting LEIN_ROOT.
      LEIN_ROOT=nbd
      DATABASE_URL=postgres://localhost/syme
    steps:
      - checkout
      # Pull the dependencies in a way that they're cached.
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: bin/lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      # Migrate the DB, then test.
      - run: bin/lein do run -m syme.db, test
      # Push it out to Heroku on a successful master build.
      - add_ssh_keys
      - deploy:
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                # Install Heroku SSH server fingerprint.
                mkdir -p ~/.ssh
                echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

                git config --global push.default simple
                git push -f git@heroku.com:syme.git
              fi
